common: 
    exp_name: pycda_exp001
    arch_encoder: resnet101_dilated8
    arch_decoder: ppm_bilinear
    arch_reconst:
    arch_disc:
    weights_encoder: ./checkpoint/source_best/encoder_i_itermodel_best.pth.tar
    weights_decoder: ./checkpoint/source_best/decoder_i_itermodel_best.pth.tar
    weights_reconst:
    weights_disc:
    use_aux: True
    num_gpus: 2
    target: cityscapes
    syncbn: True
    batch_size: 8
    iter_size: 1
    num_workers: 4
    gaussian_kernel_size: 5
    gaussian_sigma: 0.8
    data_dir: /data/lianqing//workspace/Adapt_seg/data/GTA5
    data_list: ./dataset/gta5_list/train.txt
    ignore_label: 255
    input_size: 1024,560
    data_dir_target: /data/lianqing/workspace/Adapt_seg/data/Cityscapes
    data_list_target: ./dataset/cityscapes_list/train2.txt
    input_size_target: 1024,512
    input_size_crop: 560, 480
    input_size_target_crop: 560, 480
    fc_dim: 2048
    decoder: True
    disc: False
    reconst: False
    lr_pow: 0.9
    conf_threshold: 0.5
    #loss weight
    lambda_pseudo: 1
    lambda_soft_pseudo: 0.025
    lambda_balance: 1
    # learning rate
    lr_encoder: 0.00016
    lr_decoder: 0.0016
    lr_disc: 0.0016
    lambda_seg: 0.4
    decrease_lr: -1
    lambda_trade_off: 1
    is_training: True
    lambda_adv_target1: 0
    lambda_adv_target2: 0
    #lambda_adv_multiscale: 0.00025
    merge_1x1: False
    box_size: [4, 8]
    box_threshold: [0.5]
    lambda_box_pseudo: [0.05]
    beta1: 0.9
    print_freq: 10
    num_classes: 19
    num_steps: 35000
    power: 0.9
    ignore_index: 255
    rotate_min: -10
    rotate_max: 10
    scale_min: 0.5
    scale_max: 1.5
    max_num_bbx: 2000
    nms_threshold: 0.3
    random_scale: False
    random_mirror: False
    random_seed: 1234
    restore_from: False 
    save_pred_every: 1000
    snapshot_dir: ./snapshots/
    weight_decay: 0.0005
    set: train
    com_size: 2048,1024
    input_size_test: 1024,512
    result_dir: test_IoU.txt
    data_list_target_val: ./dataset/cityscapes_list/val2.txt
    data_dir_target_val: /data/lianqing/workspace/Adapt_seg/data/Cityscapes/gtFine/train
    data_list_target_test: ./dataset/cityscapes_list/val.txt
    data_dir_target_test: /data/lianqing/workspace/Adapt_seg/data/Cityscapes/gtFine/val
    label_path_list_val: ./dataset/cityscapes_list/label2.txt
    
